name: Deploy Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest 

    steps:
    - name: Kodu İndir (Checkout)
      uses: actions/checkout@v4

    - name: .NET Kur
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    # 🔥 KESİN ÇÖZÜM: Klasörün içindeki tam dosya adını (uzantısıyla birlikte) verdik
    - name: Projeyi Derle (Build)
      run: dotnet build SmartAttendance/SmartAttendance.WebApi.csproj --configuration Release

    - name: Projeyi Paketle (Publish)
      run: dotnet publish SmartAttendance/SmartAttendance.WebApi.csproj -c Release -o ./publish_output

    - name: Azure'a Yükle (Deploy)
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'smartattendance-ffhxgvbsd6h7ancr' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish_output